# Generated by Django 3.0.8 on 2020-07-28 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usereducationskill', '0002_auto_20200728_2212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillsetrel',
            unique_together={('skill', 'user')},
        ),
    ]
