# Generated by Django 3.0.8 on 2020-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeaddress',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='line1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='line2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='line3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
