# Generated by Django 3.0.8 on 2020-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20200722_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
