# Generated by Django 3.0.8 on 2020-07-22 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0004_auto_20200722_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinValueValidator(7)]),
        ),
    ]
