# Generated by Django 3.0.8 on 2020-07-22 10:55

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_auto_20200722_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=10),
        ),
    ]
