# Generated by Django 3.0.8 on 2020-07-23 06:54

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0007_auto_20200722_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=11),
        ),
    ]
