# Generated by Django 3.0.8 on 2020-07-23 06:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0008_auto_20200723_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=12),
        ),
    ]
