# Generated by Django 3.0.8 on 2020-08-03 19:35

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0010_auto_20200803_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=12),
        ),
    ]
