# Generated by Django 3.0.7 on 2020-07-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_skillset_skillsetrel'),
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_skill', to='user.Skillset'),
        ),
    ]
