# Generated by Django 3.0.7 on 2020-07-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_skillset_skillsetrel'),
        ('qa', '0002_auto_20200715_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_user', to='user.UserDetails'),
        ),
    ]
