# Generated by Django 3.0.7 on 2020-07-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_skillset_skillsetrel'),
        ('qa', '0003_auto_20200715_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to='user.UserDetails'),
        ),
    ]
