# Generated by Django 3.0.8 on 2020-07-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20200715_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
