# Generated by Django 3.0.8 on 2020-08-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquestion', '0002_auto_20200803_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comments',
            new_name='comments',
        ),
    ]
