# Generated by Django 3.0.8 on 2020-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquestion', '0003_auto_20200804_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
