# Generated by Django 3.0.8 on 2020-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquestion', '0004_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
