# Generated by Django 3.0.7 on 2020-07-09 10:22

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default=builtins.abs, max_length=20),
            preserve_default=False,
        ),
    ]
