# Generated by Django 3.0.7 on 2020-07-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
