# Generated by Django 3.0.7 on 2020-07-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_email_mobile_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='user.UserDetails'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='user.UserDetails'),
        ),
    ]
