# Generated by Django 3.0.7 on 2020-07-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200709_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=11)),
                ('line2', models.CharField(max_length=11)),
                ('line3', models.CharField(max_length=11)),
                ('landmark', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=11)),
                ('pin', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resaddress', to='user.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=11)),
                ('line2', models.CharField(max_length=11)),
                ('line3', models.CharField(max_length=11)),
                ('landmark', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=11)),
                ('pin', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offaddress', to='user.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='EducationRelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_relation', to='user.Board')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relation', to='user.Course')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_relation', to='user.Education')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to='user.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='user.Education'),
        ),
        migrations.AddField(
            model_name='board',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='user.Course'),
        ),
    ]
