# Generated by Django 3.0.8 on 2020-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_skillset_skillsetrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email_id',
            field=models.EmailField(default=1, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='landmark',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='line1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='line2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='line3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resaddress',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='mainskill',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
