# Generated by Django 3.0.8 on 2020-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200717_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email_id',
            field=models.EmailField(default=1, max_length=20, unique=True),
        ),
    ]
