# Generated by Django 3.0.8 on 2020-07-21 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa', '0005_auto_20200721_1108'),
        ('user', '0011_auto_20200720_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationreluser',
            name='board',
        ),
        migrations.RemoveField(
            model_name='educationreluser',
            name='course',
        ),
        migrations.RemoveField(
            model_name='educationreluser',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='educationreluser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='officeaddress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='resaddress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='skillsetrel',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='skillsetrel',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='user_id',
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='email_mul', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_mul', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='EducationRelUser',
        ),
        migrations.DeleteModel(
            name='OfficeAddress',
        ),
        migrations.DeleteModel(
            name='ResAddress',
        ),
        migrations.DeleteModel(
            name='Skillset',
        ),
        migrations.DeleteModel(
            name='skillsetRel',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
