# Generated by Django 3.0.8 on 2020-07-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200720_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email_id',
        ),
    ]
