# Generated by Django 3.0.8 on 2020-07-28 22:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usereduskill', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationreluser',
            unique_together={('user', 'degree', 'course', 'board')},
        ),
    ]
